version = 3.7.17
runner.dialect = scala213

maxColumn = 120
align.preset = more
align.openParenDefnSite = false
align.openParenCallSite = false

rewrite.rules = [
  RedundantBraces,
  RedundantParens,
  SortModifiers,
  PreferCurlyFors
]

rewrite.redundantBraces.stringInterpolation = true
rewrite.redundantBraces.generalExpressions = true

newlines.topLevelStatementBlankLines = [
  {
    blanks { before = 1 }
  }
]

docstrings.style = Asterisk
docstrings.wrap = no
